# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://aerosmp.tk"
baseurl: "/aerosmp"
siteIcon: media/android-chrome-192x192.png
siteYear: 2020
siteFooterlink: https://aerosmp.tk
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Aero SMP
serverDescription: Survive in the paradise
serverIP: mc.aerosmp.tk:25565


# Discord information
discordInvite: https://discord.gg/9U9TmDebpb
discordServerID: 794745330875891753
discordChannelID: 794793516865421324


# Navbar Links at the top of the page
# Uncomment this section to add page functionality!
# siteNav:
#   - nname: Player Guide
#     nurl: guide
#   - nname: About
#     nurl: about


# Build settings
theme: minima
# plugins:
#   - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
